name: Convert Markdown to HTML

on: push

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=index.html
            index.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Convert Markdown to HTML [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
