name: Convert Changed Markdown to HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Get list of changed Markdown files
      id: changed
      run: |
        git fetch origin main
        git diff --name-only HEAD^ HEAD | grep '\.md$' || true > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt

    - name: Convert only changed Markdown to HTML
      run: |
        while IFS= read -r mdfile; do
          [ -f "$mdfile" ] || continue  # Skip if file was deleted
          htmlfile="${mdfile%.md}.html"
          echo "Converting $mdfile -> $htmlfile"
          pandoc "$mdfile" -o "$htmlfile"
        done < changed_files.txt

    - name: Commit and push HTML files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git diff --cached --quiet || git commit -m "Update HTML from modified Markdown"
        git push
      continue-on-error: true