name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: docker://pandoc/core:2.9
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          -f markdown
          -t html5 
          --toc
          --output=index.html
          index.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.html
          git commit -m "Convert Markdown to HTML [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



















    - uses: docker://pandoc/core:2.9
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          -f markdown
          -t html5 
          --toc
          --output=index.html
          index.md

    - name: Retrieve Git Config
      id: git-config
      run: |
        FIRST_COMMIT=$(git log --reverse --format=%H | head -n 1)
        AUTHOR_NAME=$(git log --format='%an' -n 1 $FIRST_COMMIT)
        AUTHOR_EMAIL=$(git log --format='%ae' -n 1 $FIRST_COMMIT)
        git config --local user.email $AUTHOR_EMAIL
        git config --local user.name $AUTHOR_NAME
        git add .
        git commit -m "Update content" 

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push