name: Convert to HTML

on: push

permissions:
  contents: read

jobs:
  convert_to_html:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: docker://pandoc/core:2.9
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          -f markdown
          -t html5 
          --toc
          --output=index.html
          index.md

    - name: Retrieve Git Config
      id: git-config
      run: |
        FIRST_COMMIT=$(git log --reverse --format=%H | head -n 1)
        AUTHOR_NAME=$(git log --format='%an' -n 1 $FIRST_COMMIT)
        AUTHOR_EMAIL=$(git log --format='%ae' -n 1 $FIRST_COMMIT)
        git config --local user.email $AUTHOR_EMAIL
        git config --local user.name $AUTHOR_NAME
        git add .
        git commit -m "Update content" 

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push